{
  "bucketName": "cabmaster",
  "sseAlgorithm": null,
  "ongoingRestore": false,
  "storageClass": null,
  "sseCustomerAlgorithm": null,
  "contentDisposition": null,
  "contentEncoding": null,
  "contentType": "text/csv",
  "key": "cabMaster.csv",
  "sseCustomerKeyMd5": null,
  "contentMD5": null,
  "requesterCharged": false,
  "replicationStatus": null,
  "cacheControl": null,
  "httpExpiresDate": null,
  "sseAwsKmsKeyId": null,
  "versionId": null,
  "restoreExpirationTime": null,
  "expirationTimeRuleId": null,
  "expirationTime": null,
  "contentLanguage": null,
  "etag": "9e52dd25f9716f4de9b7ab369ecdb609",
  "contentLength": 232,
  "lastModified": |2022-01-14T20:07:48|,
  "userMetadata": {},
  "redirectLocation": null
}